FROM python:3.9.13
WORKDIR /Wawu/Server
COPY requirements.txt .
RUN pip install -r ./requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY ./Core ./Core
COPY ./Data ./Data
COPY ./Lib ./Lib
COPY ./Resources ./Resources
COPY ./Log ./Log
COPY run.py .

EXPOSE 8080

CMD ["python", "./run.py"]